import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { existsSync, mkdirSync, copyFileSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Deploy artifacts into a vault's plugin folder after every successful build
// (dev watch rebuilds included). Override the vault root with INKSWELL_VAULT.
const VAULT = process.env.INKSWELL_VAULT || "X:/DKB";
const PLUGIN_DIR = join(VAULT, ".obsidian", "plugins", "inkswell");
const ARTIFACTS = ["main.js", "manifest.json", "styles.css"];

const deployPlugin = {
  name: "deploy-to-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return; // don't deploy a broken build
      try {
        if (!existsSync(PLUGIN_DIR)) mkdirSync(PLUGIN_DIR, { recursive: true });
        for (const file of ARTIFACTS) {
          if (existsSync(file)) copyFileSync(file, join(PLUGIN_DIR, file));
        }
        console.log(`[deploy] artifacts -> ${PLUGIN_DIR}`);
      } catch (e) {
        console.warn(`[deploy] skipped: ${e.message}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [deployPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
